backtest_period: 1y
default_strategy: ai_model_strategy
default_tickers:
- AAPL
- MSFT
- GOOG
initial_capital: 100000
interval: 1d
model_classifier_path: ai/logistic_model.pkl
model_regressor_path: ai/rf_model.pkl
rsi_buy_threshold: 30
rsi_sell_threshold: 70
sma_long_window: 200
sma_short_window: 50
timeframe: 1y
